### PR TITLE
fix: handle fast-jwt decode error properly

### LINKED ISSUE #274: Server returns 500 if token malformed. Should return 401.
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Server returns 401 if token is not valid, but returns 500 if token is malformed.
How to make it also return 401 in this case?

### PR DESCRIPTION
**Pull request by erfanium**
fixes #274 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by erfanium** [comment]
tests are broken, because i don't know how i can eliminate those coverage errors. spend like 2 hours to get rid of that bad i couldn't.

**Comment by mcollina** [comment]
I'm not sure what's the problem with test coverage, as tests are not passing at all

**Comment by mcollina** [comment]
Fixed.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by erfanium** [comment]
@mcollina 
Thanks!
I have forgotten to change that `t.plan(...)`. but the `tap` error message wasn't says the reason.

**Pull request merged**
