### PR TITLE
Update examples to use onRequest hook

### PR DESCRIPTION
**Pull request by cemremengu**
Examples should suggest using `preValidation` since it is a better approach

### CODE REVIEW

**Comment by mcollina** [comment]
I think it's better to wait for https://github.com/fastify/help/issues/37 to settle. It might be that we would have to tweak these hooks again before 2.0.0 exits the rc period.

**Comment by cemremengu** [comment]
@mcollina I think this is ok now that we are keeping `preValidation`

**Comment by mcollina** [comment]
This should be `preParsing` or even `onRequest`.

**Comment by cemremengu** [comment]
@mcollina LGTY?

**Pull request merged**
